# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_disease_genes', '0002_auto_20160104_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genedisease',
            name='DiseaseID',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='GeneID',
        ),
        migrations.AddField(
            model_name='clinvardisease',
            name='Genes',
            field=models.ManyToManyField(to='find_disease_genes.ClinvarGene'),
        ),
        migrations.DeleteModel(
            name='GeneDisease',
        ),
    ]
