# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_disease_genes', '0006_auto_20160105_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvardisease',
            name='SourceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='find_disease_genes.ClinvarSource'),
        ),
    ]
