# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_disease_genes', '0008_auto_20160105_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvardisease',
            name='DiseaseName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clinvargene',
            name='GeneName',
            field=models.CharField(max_length=120),
        ),
    ]
