# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_disease_genes', '0010_auto_20160106_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medgenconcept',
            name='RelatedConcepts',
            field=models.ManyToManyField(blank=True, related_name='_medgenconcept_RelatedConcepts_+', to='find_disease_genes.MedgenConcept'),
        ),
    ]
