# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_disease_genes', '0014_auto_20160106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medgenconcept',
            name='Def',
            field=models.CharField(max_length=10000),
        ),
    ]
