# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_disease_genes', '0015_auto_20160106_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvardisease',
            name='id',
        ),
        migrations.AlterField(
            model_name='clinvardisease',
            name='ConceptID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
